In [71]:
import pandas as pd
import ipywidgets as widgets
from pandas import ExcelWriter
import os

In [81]:
df=pd.read_excel("timesheet_sample file.xls",sheet_name="All projects",skiprows=7)

In [82]:
df=df.fillna(0)

In [83]:
df=df.iloc[0:10160,:]

In [84]:
df

,Task,Daily Log,Date,User,Hours(For Calculation),Project Name,Billing Status
0,Ads - Campaign Optimisation,02:00,15-05-2020,Anfal Aboobacker,2,Sleep Mantra - Amazon Ads,Billable
1,Misc,01:30,15-05-2020,Anfal Aboobacker,1.5,Sleep Mantra - Amazon Ads,Billable
2,Ads - Campaign Optimisation,02:00,14-05-2020,Anfal Aboobacker,2,Sleep Mantra - Amazon Ads,Billable
3,Internal Discussions,00:30,14-05-2020,Anfal Aboobacker,0.5,Sleep Mantra - Amazon Ads,Non Billable
4,Misc,01:30,14-05-2020,Anfal Aboobacker,1.5,Sleep Mantra - Amazon Ads,Billable
...,...,...,...,...,...,...,...
10155,Project Management & Review,03:30,03-04-2020,Tushar Kumar,3.5,Pilgrim - Personal Care Website,Non Billable
10156,Tasks as per - Pilgrim Requirments Checklist s...,09:00,02-04-2020,Sanyogita Parab,9,Pilgrim - Personal Care Website,Billable
10157,Phase 3 co ordination activities,01:00,02-04-2020,Sitaram Abhishek,1,Pilgrim - Personal Care Website,Billable
10158,Bug Fixes,01:00,01-04-2020,Sharzil Shaikh,1,Pilgrim - Personal Care Website,Billable
10159,Project Management & Review,03:00,01-04-2020,Tushar Kumar,3,Pilgrim - Personal Care Website,Non Billable

In [85]:
projects=df['Project Name'].unique()

In [87]:
with pd.ExcelWriter('Projects1.xlsx') as writer:  
    
    for i in range(len(projects)):
        p= projects[i]
        newdf=df[df['Project Name']==p]
        p=p.replace(":","")
        sheetname=p[:30]
        newdf.to_excel(writer,sheet_name=sheetname)
        newdf.style.apply(lambda x: ["background-color: #ff33aa" 
                          if (i >= 6 and (v =='Billable')) 
                          else "" for i, v in enumerate(x)], axis = 1)
        del sheetname
        del newdf

In [89]:
newdf=df[df['Project Name']==p]
newdf.style.apply(lambda x: ["background-color: #ff33aa" 
                          if (i >= 6 and (v =='Billable')) 
                          else "" for i, v in enumerate(x)], axis = 1)
newdf

,Task,Daily Log,Date,User,Hours(For Calculation),Project Name,Billing Status
10005,Website back end development,02:00,15-05-2020,Suman Kumar,2,Pilgrim - Personal Care Website,Billable
10006,"Reviews -Show first 3 reviews, and then show R...",06:00,15-05-2020,Suman Kumar,6,Pilgrim - Personal Care Website,Billable
10007,Website back end development,06:00,14-05-2020,Suman Kumar,6,Pilgrim - Personal Care Website,Billable
10008,Discussions and requirment gathering,01:30,14-05-2020,Sitaram Abhishek,1.5,Pilgrim - Personal Care Website,Billable
10009,Discussions and requirment gathering,00:30,14-05-2020,Sitaram Abhishek,0.5,Pilgrim - Personal Care Website,Non Billable
...,...,...,...,...,...,...,...
10155,Project Management & Review,03:30,03-04-2020,Tushar Kumar,3.5,Pilgrim - Personal Care Website,Non Billable
10156,Tasks as per - Pilgrim Requirments Checklist s...,09:00,02-04-2020,Sanyogita Parab,9,Pilgrim - Personal Care Website,Billable
10157,Phase 3 co ordination activities,01:00,02-04-2020,Sitaram Abhishek,1,Pilgrim - Personal Care Website,Billable
10158,Bug Fixes,01:00,01-04-2020,Sharzil Shaikh,1,Pilgrim - Personal Care Website,Billable
10159,Project Management & Review,03:00,01-04-2020,Tushar Kumar,3,Pilgrim - Personal Care Website,Non Billable

In [129]:
sm=df[df['Project Name']=='YogaBar - Amazon Marketing']

In [130]:
sm['Date']=pd.to_datetime(sm['Date'],format='%d-%m-%Y')

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [131]:
sm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 246 entries, 3560 to 3805
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Task                    246 non-null    object
 1   Daily Log               246 non-null    object
 2   Date                    246 non-null    datetime64[ns]
 3   User                    246 non-null    object
 4   Hours(For Calculation)  246 non-null    object
 5   Project Name            246 non-null    object
 6   Billing Status          246 non-null    object
dtypes: datetime64[ns](1), object(6)
memory usage: 15.4+ KB

In [136]:
sm['Month'] = sm['Date'].map(lambda x:  x.month_name)

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [133]:
sm['Hours(For Calculation)'] = sm['Hours(For Calculation)'].map(lambda x:  float(x))

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [134]:
sm

,Task,Daily Log,Date,User,Hours(For Calculation),Project Name,Billing Status,Month
3560,Internal Discussion,01:00,2020-05-15,Manisha Kabi,1.00,YogaBar - Amazon Marketing,Non Billable,5
3561,Campaign Monitoring and Optimization,00:30,2020-05-15,Manisha Kabi,0.50,YogaBar - Amazon Marketing,Non Billable,5
3562,Internal Discussion,01:30,2020-05-15,Rushab Luhade,1.50,YogaBar - Amazon Marketing,Non Billable,5
3563,Project Management,00:45,2020-05-15,Srishti Jalan,0.75,YogaBar - Amazon Marketing,Non Billable,5
3564,Project Management,04:00,2020-05-15,Srishti Jalan,4.00,YogaBar - Amazon Marketing,Non Billable,5
...,...,...,...,...,...,...,...,...
3801,Project Initiation,00:30,2020-04-16,Rushab Luhade,0.50,YogaBar - Amazon Marketing,Non Billable,4
3802,A+ Content Review,01:30,2020-04-16,Srishti Jalan,1.50,YogaBar - Amazon Marketing,Billable,4
3803,Internal Discussion,00:15,2020-04-16,Srishti Jalan,0.25,YogaBar - Amazon Marketing,Non Billable,4
3804,Internal Discussion,00:30,2020-04-16,Rushab Luhade,0.50,YogaBar - Amazon Marketing,Non Billable,4
3805,Project Management,00:30,2020-04-16,Srishti Jalan,0.50,YogaBar - Amazon Marketing,Non Billable,4

In [135]:
import numpy as np
pd.pivot_table(sm,values='Hours(For Calculation)',index=['User','Billing Status'],columns='Month',aggfunc=np.sum)

Month                              4      5
User           Billing Status
Manisha Kabi   Billable         7.25   3.50
               Non Billable    13.50  10.75
Piyush Gupta   Billable        19.00  14.50
               Non Billable    44.00  34.92
Rushab Luhade  Billable        38.50  35.50
               Non Billable    31.00  28.50
Srishti Jalan  Billable        22.00  17.50
               Non Billable    21.42  33.00
Srishti Shetty Billable        18.50   8.00
               Non Billable     2.50   0.50